---
- name: download alp binary
  get_url:
    url: https://github.com/tkuchiki/alp/releases/download/v1.0.10/alp_linux_amd64.tar.gz
    dest: /tmp/alp_linux_amd64.tar.gz
  register: alp

- name: install alp
  unarchive:
    remote_src: yes
    src: /tmp/alp_linux_amd64.tar.gz
    dest: /usr/local/bin/
  when: alp.changed