---
- name: download delta package
  get_url:
    url: https://github.com/dandavison/delta/releases/download/0.13.0/git-delta_0.13.0_amd64.deb
    dest: /tmp/git-delta_0.13.0_amd64.deb
  register: delta

- name: install delta
  apt:
    deb: /tmp/git-delta_0.13.0_amd64.deb
  when: delta.changed
