---
- name: download delta package
  get_url:
    url: https://github.com/dandavison/delta/releases/download/{{ delta.version }}/git-delta_{{ delta.version }}_{{ machine.arch }}.deb
    dest: /tmp/git-delta_{{ delta.version }}_{{ machine.arch }}.deb
  register: install_delta

- name: install delta
  apt:
    deb: /tmp/git-delta_{{ delta.version }}_{{ machine.arch }}.deb
  when: install_delta.changed
