---
- name: download slp binary
  get_url:
    url: https://github.com/tkuchiki/slp/releases/download/v0.1.2/slp_linux_amd64.tar.gz
    dest: /tmp/slp_linux_amd64.tar.gz
  register: install_slp

- name: install slp
  unarchive:
    remote_src: yes
    src: /tmp/slp_linux_amd64.tar.gz
    dest: /usr/local/bin/
  when: install_slp.changed