---
- name: download go binary
  get_url:
    url: "https://go.dev/dl/go{{ go.version }}.linux-{{ machine.arch }}.tar.gz"
    checksum: "sha256:{{ go.checksum }}"
    dest: "/tmp/go{{ go.version }}.linux-{{ machine.arch }}.tar.gz"

- name: install go
  unarchive:
    remote_src: yes
    src: "/tmp/go{{ go.version }}.linux-{{ machine.arch }}.tar.gz"
    dest: /opt/

- name: add to PATH
  blockinfile:
    path: /home/isucon/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK [go]"
    block: |
      export GOROOT=/opt/go
      export GOPATH=$HOME/go
      export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
