---
- name: download cloudwatch agent package
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /tmp/amazon-cloudwatch-agent.deb
  register: cloudwatch_agent

- name: install cloudwatch-agent
  apt:
    deb: /tmp/amazon-cloudwatch-agent.deb
  when: cloudwatch_agent.changed

- name: copy credentials
  copy:
    src: credentials
    dest: /home/cwagent/.aws/

- name: update agent settings
  template:
    src: config.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/config.json
  register: cloudwatch_agent_settings

- name: start agent
  shell: |
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
      -a fetch-config \
      -m onPremise \
      -s \
      -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json
  when: cloudwatch_agent_settings.changed
