---
- name: copy credentials
  copy:
    src: "{{ item[1] }}"
    dest: "{{ item[0].dest }}"
    owner: "{{ item[0].user }}"
    group: "{{ item[0].user }}"
    mode: "600"
  with_nested:
    - [
        { user: "root", dest: "/root/.ssh/" },
        {
          user: "{{ login.username }}",
          dest: "/home/{{ login.username }}/.ssh/",
        },
      ]
    # TODO: 変数にする
    - ["id_ed25519", "id_ed25519.pub"]
