---
- name: add git settings
  copy:
    src: .gitconfig
    dest: "/home/{{ login.username }}/.gitconfig"
    owner: "{{ login.username }}"
    group: "{{ login.username }}"
- name: clone repo
  become_user: "{{ login.username }}"
  git:
    repo: "{{ repository.remote }}"
    dest: "{{ repository.dest }}"
    accept_hostkey: yes
