---
- name: download pprotein binary
  get_url:
    url: "https://github.com/kaz/pprotein/releases/download/{{ pprotein.version }}/pprotein_{{ pprotein.version }}_linux_amd64.tar.gz"
    dest: "/tmp/pprotein_{{ pprotein.version }}_linux_amd64.tar.gz"

- name: install pprotein
  unarchive:
    remote_src: yes
    src: "/tmp/pprotein_{{ pprotein.version }}_linux_amd64.tar.gz"
    dest: /usr/local/bin/

- name: install pprotein service
  copy:
    src: pprotein.service
    dest: /etc/systemd/system/pprotein.service
  when: run_pprotein_server
  notify: ensure pprotein enabled

- name: install pprotein-agent service
  copy:
    src: pprotein-agent.service
    dest: /etc/systemd/system/pprotein-agent.service
  notify: ensure pprotein-agent enabled

- name: ensure pprotein disabled
  systemd:
    name: pprotein
    enabled: no
    state: stopped
  ignore_errors: true
  tags: 
    - never
    - cleanup

- name: ensure pprotein-agent disabled
  systemd:
    name: pprotein-agent
    enabled: no
    state: stopped
  tags: 
    - never
    - cleanup
