---
- name: download pprotein binary
  get_url:
    url: "https://github.com/kaz/pprotein/releases/download/{{ pprotein.version }}/pprotein_{{ pprotein.version }}_linux_amd64.tar.gz"
    dest: "/tmp/pprotein_{{ pprotein.version }}_linux_amd64.tar.gz"

- name: install pprotein
  unarchive:
    remote_src: yes
    src: "/tmp/pprotein_{{ pprotein.version }}_linux_amd64.tar.gz"
    dest: /usr/local/bin/

- name: install pprotein service
  copy:
    src: pprotein.service
    dest: /etc/systemd/system/pprotein.service
  when: run_pprotein_server
  notify: start pprotein

- name: install pprotein-agent service
  copy:
    src: pprotein-agent.service
    dest: /etc/systemd/system/pprotein-agent.service
  notify: start pprotein-agent
